
[build]
  publish = "out"
  command = "npm run build:static"

[build.environment]
  NODE_VERSION = "20"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.deploy-preview]
  command = "npm run build:static"

[context.branch-deploy]
  command = "npm run build:static"